### ISSUE TITLE
Dinner

### ISSUE THREAD

**Issue by cristobalescobar** [IntroToCode/RecipesCodemates2#4]
## 💬 Discussion topic

Dinner

## ❗ Potential issues

Need some recipes

## 👥 People to consult

@vhuang13 @erikahirata @tmullin-1 @

## 📃 Details

Send me some pdfs

**Comment by erikahirata** [comment]
Do you have any food restrictions?

**Comment by cristobalescobar** [comment]
Meat for dinner? @erikahirata

**Comment by vhuang13** [comment]
Closing the issue since the dinner recipe is completed!
